# Generated by Django 5.2.3 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Artist'), ('2', 'Organiser')], default='1', max_length=50, verbose_name='User Type'),
        ),
    ]
