# Generated by Django 5.2.3 on 2025-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Artist'), ('2', 'Organiser')], default='1', max_length=2, verbose_name='User Type'),
        ),
    ]
