# Generated by Django 5.2.3 on 2025-08-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_flag',
            field=models.BooleanField(null=True),
        ),
    ]
