# Generated by Django 5.2.3 on 2025-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_datetime_event_date_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name_slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='sqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
