# Generated by Django 5.2.3 on 2025-08-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_name_slug_event_sqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sqid',
        ),
    ]
