# Generated by Django 5.2.3 on 2025-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_sqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name_slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
