# Generated by Django 5.2.3 on 2025-08-26 19:44

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.Event.event_directory_path),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
