# Generated by Django 5.2.3 on 2026-01-16 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_discipline_profiledisciplines'),
        ('event', '0007_cast_castingapplications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cast_disciplines', to='account.discipline'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='final_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_castings', to=settings.AUTH_USER_MODEL, to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='castingapplications',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_applications', to=settings.AUTH_USER_MODEL, to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='castingapplications',
            name='cast_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_applications', to='event.cast', to_field='public_id'),
        ),
    ]
